### ISSUE TITLE
The Name

### ISSUE THREAD

**Issue by jebotz** [opentffoundation/opentf#287] opened 2023-09-05 22:23 UTC
### OpenTF Version

```shell
-
```

### Use Cases

-

### Attempted Solutions

-

### Proposal

It has been mentioned that the name probably needs to change again because OpenTF may still infringe Haschicorp's trademarks.  The software previously known as terraform has in recent years become almost synonymous with "Infrastructure as Code", so maybe the new name should reflect this and be deliberately generic... the project could be called something like "InfraCode" and the actual executable "iac".  Or slightly less generic, both project and executable could be something like "infrabuilder" or (this one has a nice ring) "infratect".

**Comment by DicsyDel** [comment] 2023-09-05 22:27
Hi @jebotz,

Thanks a lot for your input. We're thinking along the same lines and working with legal to find an acceptable name.

Regards,
Igor

**Comment by dylanmtaylor** [comment] 2023-09-06 00:41
Duplicate of #276

**Comment by ErikHumphrey** [comment] 2023-09-06 00:43
`ic` would be confused with Infracost. `iac` would work, though.

**Comment by roni-frantchi** [comment] 2023-09-06 10:04
Hey everyone thanks very much for the feedback and discussion!  
There are two other issues opened that kick off a discussion very similar to this one, and so we've created https://github.com/opentffoundation/opentf/issues/296 to keep the discussions going in one place.  

We'd love to keep this discussion going there! 🙏

**Closed by roni-frantchi** 2023-09-06 10:04 UTC
Labels: enhancement
